services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ipmoney
      POSTGRES_PASSWORD: ipmoney
      POSTGRES_DB: ipmoney
    ports:
      - "5432:5432"
    volumes:
      - ipmoney_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ipmoney_redis:/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ipmoney_minio:/data

volumes:
  ipmoney_postgres:
  ipmoney_redis:
  ipmoney_minio:

